"""Add updated_at to blood_donors

Revision ID: 4e9fc9e07bc5
Revises: 1773aede24e8
Create Date: 2025-06-27 03:15:17.420250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9fc9e07bc5'
down_revision: Union[str, Sequence[str], None] = '1773aede24e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
