"""reset_and_sync_all_models_no_geo

Revision ID: 71da2c499d29
Revises: 
Create Date: 2026-01-21 21:45:48.998382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71da2c499d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('blood_type', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_blood_donors_id'), 'blood_donors', ['id'], unique=False)
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('needed_units', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_requests_id'), 'blood_requests', ['id'], unique=False)
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('room_name', sa.String(length=255), nullable=False),
    sa.Column('caller_id', sa.String(length=128), nullable=False),
    sa.Column('callee_ids', sa.JSON(), nullable=True),
    sa.Column('callee_type', sa.String(length=64), nullable=True),
    sa.Column('call_mode', sa.Enum('VOICE', 'VIDEO', name='callmode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ENDED', 'MISSED', 'CANCELLED', name='callstatus', native_enum=False), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_caller_id'), 'call_sessions', ['caller_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_id'), 'call_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_call_sessions_room_name'), 'call_sessions', ['room_name'], unique=False)
    op.create_index(op.f('ix_call_sessions_session_id'), 'call_sessions', ['session_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_table('healthcare_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('service_type', sa.Enum('doctor', 'nurse', 'lab', name='providertype'), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_providers_id'), 'healthcare_providers', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False, comment='doctor | nurse | taxi | biker | blood_request | etc'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_tx_id', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', 'AWAITING_VERIFICATION', name='payment_status', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When a pending payment becomes invalid'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when admin confirms payment'),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_expires_at'), 'payments', ['expires_at'], unique=False)
    op.create_index('ix_payments_expiry_pending', 'payments', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index('ix_payments_provider_status', 'payments', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_payments_provider_tx_id'), 'payments', ['provider_tx_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_user_phone'), 'payments', ['user_phone'], unique=False)
    op.create_index('ix_payments_user_service_created', 'payments', ['user_id', 'service_type', 'created_at'], unique=False)
    op.create_table('transport_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_offers_id'), 'transport_offers', ['id'], unique=False)
    op.create_table('transport_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_requests_id'), 'transport_requests', ['id'], unique=False)
    op.create_table('usage_counter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_type', name='uq_user_service')
    )
    op.create_index(op.f('ix_usage_counter_service_type'), 'usage_counter', ['service_type'], unique=False)
    op.create_index(op.f('ix_usage_counter_user_id'), 'usage_counter', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('healthcare_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['healthcare_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_requests_id'), 'healthcare_requests', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_healthcare_requests_id'), table_name='healthcare_requests')
    op.drop_table('healthcare_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_counter_user_id'), table_name='usage_counter')
    op.drop_index(op.f('ix_usage_counter_service_type'), table_name='usage_counter')
    op.drop_table('usage_counter')
    op.drop_index(op.f('ix_transport_requests_id'), table_name='transport_requests')
    op.drop_table('transport_requests')
    op.drop_index(op.f('ix_transport_offers_id'), table_name='transport_offers')
    op.drop_table('transport_offers')
    op.drop_index('ix_payments_user_service_created', table_name='payments')
    op.drop_index(op.f('ix_payments_user_phone'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_tx_id'), table_name='payments')
    op.drop_index('ix_payments_provider_status', table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index('ix_payments_expiry_pending', table_name='payments')
    op.drop_index(op.f('ix_payments_expires_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_healthcare_providers_id'), table_name='healthcare_providers')
    op.drop_table('healthcare_providers')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_call_sessions_session_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_room_name'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_caller_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_blood_requests_id'), table_name='blood_requests')
    op.drop_table('blood_requests')
    op.drop_index(op.f('ix_blood_donors_id'), table_name='blood_donors')
    op.drop_table('blood_donors')
    # ### end Alembic commands ###
