"""Fix city and hospital lengths

Revision ID: d5491939629c
Revises: 3a8d0e640054
Create Date: 2025-06-28 06:18:33.398472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5491939629c'
down_revision: Union[str, Sequence[str], None] = '3a8d0e640054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blood_donors', 'city',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blood_donors', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
